site_name: 'Posit Connect: rsconnect-python'
copyright: Posit Software, PBC. All Rights Reserved

markdown_extensions:
  - toc:
      permalink: "#"
  - attr_list: {}
  - def_list: {}
  - tables: {}
  - admonition
  - pymdownx.superfences: {}
  - codehilite:
      guess_lang: false

plugins:
  - macros
  - search

nav:
  - index.md
  - changelog.md

theme:
  name: material
  custom_dir: overrides
  font:
    text: Open Sans
  logo: 'images/iconPositConnect.svg'
  favicon: 'images/favicon.ico'
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - css/custom.css

extra:
  rsconnect_python:
    version: !!python/object/apply:os.getenv ["VERSION"]
